name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: plotconvert-linux-x86_64
            binary: target/x86_64-unknown-linux-gnu/release/plotconvert
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: plotconvert-windows-x86_64
            binary: target/x86_64-pc-windows-msvc/release/plotconvert.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo test --release --target ${{ matrix.target }}
      - run: cargo build --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.binary }}

